- client/pages/Footer.tsx
- client/pages/HomePage.tsx
> Use GitHub instead of Github

- README.md
- client/components/Markdown.tsx
- client/constants/PostList.ts
- client/pages/Footer.tsx
- client/posts/allow-to-enter-particular-characters-only/index.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/prevent-the-default-action-of-an-event/index.tsx
- client/posts/strip-html-from-a-given-text/index.tsx
- demo/allow-to-enter-particular-characters-only/index.html
- public/sitemap.xml
https://htmldom.dev/allow-to-enter-particular-characters-only
> Allow to enter particular characters only

- client/constants/PostList.ts
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/calculate-the-mouse-position-relative-to-an-element/index.tsx
- client/posts/drag-and-drop-element-in-a-list/index.tsx
- client/posts/get-the-position-of-an-element-relative-to-another/index.tsx
- client/posts/get-the-position-of-an-element-relative-to-the-document/index.tsx
- client/posts/make-a-draggable-element/index.tsx
- public/sitemap.xml
https://htmldom.dev/calculate-the-mouse-position-relative-to-an-element
> Calculate the mouse position relative to an element

- client/constants/PostList.ts
- client/posts/add-or-remove-class-from-an-element/index.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/calculate-the-mouse-position-relative-to-an-element/index.tsx
- client/posts/clone-an-element/index.tsx
- client/posts/create-an-element/index.tsx
- client/posts/drag-and-drop-element-in-a-list/index.tsx
- client/posts/drag-and-drop-table-row/index.tsx
- client/posts/get-siblings-of-an-element/index.tsx
- client/posts/insert-an-element-after-or-before-other-element/index.tsx
- client/posts/loop-over-a-nodelist/index.tsx
- client/posts/make-a-draggable-element/index.tsx
- client/posts/remove-an-element/index.tsx
- client/posts/select-an-element-or-list-of-elements/index.tsx
- client/posts/set-css-style-for-an-element/index.tsx
- demo/drag-and-drop-element-in-a-list/index.html
- demo/drag-and-drop-table-row/index.html
- public/sitemap.xml
https://htmldom.dev/drag-and-drop-table-row
> Drag and drop table row

- client/constants/PostList.ts
- client/posts/add-or-remove-class-from-an-element/index.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/calculate-the-mouse-position-relative-to-an-element/index.tsx
- client/posts/clone-an-element/index.tsx
- client/posts/create-an-element/index.tsx
- client/posts/drag-and-drop-element-in-a-list/index.tsx
- client/posts/drag-and-drop-table-column/index.tsx
- client/posts/get-siblings-of-an-element/index.tsx
- client/posts/insert-an-element-after-or-before-other-element/index.tsx
- client/posts/loop-over-a-nodelist/index.tsx
- client/posts/make-a-draggable-element/index.tsx
- client/posts/remove-an-element/index.tsx
- client/posts/select-an-element-or-list-of-elements/index.tsx
- client/posts/set-css-style-for-an-element/index.tsx
- demo/drag-and-drop-table-column/index.html
- package.json
- postcss.config.js
- public/sitemap.xml
> Drag and drop table column

- client/posts/execute-code-when-the-document-is-ready/index.tsx
> Fix the document ready post

- client/posts/get-the-first-scrollable-parent-of-an-element/index.tsx
> Remove a curly brace

- demo/sort-a-table-by-clicking-its-headers/index.html
> Fix: replace table headers inner text with buttons

- client/constants/PostList.ts
- client/pages/HomePage.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/remove-an-element/index.tsx
- client/posts/resize-an-iframe-to-fit-its-content/index.tsx
- client/posts/set-css-style-for-an-element/index.tsx
- client/posts/show-a-loading-indicator-when-an-iframe-is-being-loaded/index.tsx
- client/posts/show-or-hide-an-element/index.tsx
- public/sitemap.xml
https://htmldom.dev/show-a-loading-indicator-when-an-iframe-is-being-loaded
> feat(post): Show a loading indicator when an iframe is being loaded

- client/components/Ad.tsx
- client/components/ad.css
- client/constants/PostList.ts
- client/pages/HomePage.tsx
- client/pages/PostLayout.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/check-if-the-native-date-input-is-supported/index.tsx
- client/posts/create-a-range-slider/index.tsx
- client/posts/create-an-image-comparison-slider/index.tsx
- client/posts/create-resizable-split-views/index.tsx
- client/posts/get-siblings-of-an-element/index.tsx
- client/posts/make-a-draggable-element/index.tsx
- client/posts/set-css-style-for-an-element/index.tsx
- demo/create-a-range-slider/index.html
- public/sitemap.xml
https://htmldom.dev/create-a-range-slider
> feat(post): Create a range slider

- client/pages/Layout.tsx
Change request for the issue specified in https://github.com/phuoc-ng/html-dom/issues/137
Ability to store vertical scroll position in a variable on every location change. 
Then applying for that scroll position whenever User returns to index route from a post route.
> Storing and applying last known vertical scroll

- client/posts/execute-code-when-the-document-is-ready/index.tsx
Fix syntax error `;` in ternary
> Fix syntax error

- client/posts/create-a-range-slider/index.tsx
Small typo fix 🙂 great resources BTW! 🙏
> fix modern typo

- client/constants/PostList.ts
- client/posts/prevent-body-from-scrolling-when-opening-a-modal/index.tsx
- client/posts/set-css-style-for-an-element/index.tsx
- public/sitemap.xml
https://htmldom.dev/prevent-body-from-scrolling-when-opening-a-modal
> Prevent body from scrolling when opening a modal

- README.md
- client/constants/PostList.ts
- client/pages/Footer.tsx
- client/pages/HomePage.tsx
- client/posts/get-the-selected-text/index.tsx
- public/sitemap.xml
https://htmldom.dev/get-the-selected-text
> feat(post): Get the selected text

- client/constants/PostList.ts
- client/posts/paste-as-plain-text/index.tsx
- client/posts/select-the-text-content-of-an-element/index.tsx
- public/sitemap.xml
https://htmldom.dev/select-the-text-content-of-an-element
> feat(post): Select the text content of an element

- client/constants/PostList.ts
- client/posts/get-the-selected-text/index.tsx
- client/posts/paste-as-plain-text/index.tsx
- client/posts/save-and-restore-the-text-selection/index.tsx
- client/posts/select-the-text-content-of-an-element/index.tsx
- public/sitemap.xml
https://htmldom.dev/save-and-restore-the-text-selection
> feat(post): Save and restore the text selection

- client/constants/PostList.ts
- client/pages/Footer.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/copy-highlighted-code-to-the-clipboard/index.tsx
- client/posts/copy-text-to-the-clipboard/index.tsx
- client/posts/get-the-selected-text/index.tsx
- client/posts/paste-as-plain-text/index.tsx
- client/posts/save-and-restore-the-text-selection/index.tsx
- client/posts/select-the-text-content-of-an-element/index.tsx
- demo/copy-highlighted-code-to-the-clipboard/index.html
- package.json
- public/sitemap.xml
https://htmldom.dev/copy-highlighted-code-to-the-clipboard
> feat(post): Copy highlighted code to the clipboard

- client/components/Demo.tsx
- client/components/Markdown.tsx
- client/constants/PostList.ts
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/calculate-the-mouse-position-relative-to-an-element/index.tsx
- client/posts/create-a-range-slider/index.tsx
- client/posts/create-an-image-comparison-slider/index.tsx
- client/posts/create-resizable-split-views/index.tsx
- client/posts/drag-and-drop-element-in-a-list/index.tsx
- client/posts/drag-and-drop-table-column/index.tsx
- client/posts/drag-and-drop-table-row/index.tsx
- client/posts/drag-to-scroll/index.tsx
- client/posts/make-a-draggable-element/index.tsx
- client/posts/make-a-resizable-element/index.tsx
- client/posts/resize-columns-of-a-table/index.tsx
- client/posts/set-css-style-for-an-element/index.tsx
- client/posts/zoom-an-image/index.tsx
- demo/drag-to-scroll/index.html
- public/sitemap.xml
https://htmldom.dev/drag-to-scroll
> feat(post): Drag to scroll

- client/constants/PostList.ts
- client/posts/add-or-remove-class-from-an-element/index.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/calculate-the-mouse-position-relative-to-an-element/index.tsx
- client/posts/create-one-time-event-handler/index.tsx
- client/posts/detect-clicks-outside-of-an-element/index.tsx
- client/posts/make-a-draggable-element/index.tsx
- client/posts/prevent-the-default-action-of-an-event/index.tsx
- client/posts/set-css-style-for-an-element/index.tsx
- client/posts/show-a-custom-context-menu-at-clicked-position/index.tsx
- demo/show-a-custom-context-menu-at-clicked-position/index.html
- public/sitemap.xml
https://htmldom.dev/show-a-custom-context-menu-at-clicked-position
> feat(post): Show a custom context menu at clicked position

- client/constants/PostList.ts
- client/posts/append-to-an-element/index.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/calculate-the-mouse-position-relative-to-an-element/index.tsx
- client/posts/create-an-element/index.tsx
- client/posts/get-set-and-remove-data-attributes/index.tsx
- client/posts/loop-over-a-nodelist/index.tsx
- client/posts/prevent-the-default-action-of-an-event/index.tsx
- client/posts/show-a-custom-context-menu-at-clicked-position/index.tsx
- client/posts/show-or-hide-table-columns/index.tsx
- demo/show-or-hide-table-columns/index.html
- public/sitemap.xml
https://htmldom.dev/show-or-hide-table-columns
> feat(post): Show or hide table columns

- client/constants/PostList.ts
- client/posts/get-the-direction-of-the-text-selection/index.tsx
- client/posts/get-the-selected-text/index.tsx
- client/posts/save-and-restore-the-text-selection/index.tsx
- public/sitemap.xml
https://htmldom.dev/get-the-direction-of-the-text-selection
> feat(post): Get the direction of the text selection

- client/constants/PostList.ts
- client/posts/detect-internet-explorer-browser/index.tsx
- public/sitemap.xml
https://htmldom.dev/detect-internet-explorer-browser
> feat(post): Detect internet explorer browser

- client/constants/PostList.ts
- client/pages/HomePage.tsx
- client/posts/check-if-the-touch-events-are-supported/index.tsx
- public/sitemap.xml
https://htmldom.dev/check-if-the-touch-events-are-supported
> feat(post): Check if the touch events are supported

- client/constants/PostList.ts
- client/posts/check-if-the-touch-events-are-supported/index.tsx
- client/posts/detect-internet-explorer-browser/index.tsx
- client/posts/detect-mac-os-browser/index.tsx
- client/posts/detect-mobile-browsers/index.tsx
- public/sitemap.xml
https://htmldom.dev/detect-mobile-browsers
> feat(post): Detect mobile browsers

- client/components/Demo.tsx
- client/pages/HomePage.tsx
- client/posts/scroll-to-an-element-smoothly/index.tsx
- client/posts/scroll-to-an-element/index.tsx
- client/posts/scroll-to-top-of-the-page/index.tsx
- demo/scroll-to-an-element-smoothly/index.html
https://htmldom.dev/scroll-to-an-element-smoothly
> feat(post): Scroll to an element smoothly

- README.md
- client/constants/PostList.ts
- client/posts/get-the-position-of-an-element-relative-to-another/index.tsx
- client/posts/position-an-element-absolutely-to-another-element/index.tsx
- demo/position-an-element-absolutely-to-another-element/absolute.html
- demo/position-an-element-absolutely-to-another-element/anchor.html
- demo/position-an-element-absolutely-to-another-element/css.html
https://htmldom.dev/position-an-element-absolutely-to-another-element
> feat(post): Position an element absolutely to another element

- client/constants/PostList.ts
- client/pages/HomePage.tsx
- client/posts/check-if-an-element-is-in-the-viewport/index.tsx
- client/posts/check-if-an-element-is-visible-in-a-scrollable-container/index.tsx
https://htmldom.dev/check-if-an-element-is-visible-in-a-scrollable-container
> feat(post): Check if an element is visible in a scrollable container

- client/constants/PostList.ts
- client/posts/attach-event-handlers-inside-other-handlers/index.tsx
- client/posts/attach-or-detach-an-event-handler/index.tsx
- client/posts/create-a-custom-scrollbar/index.tsx
- client/posts/determine-the-height-and-width-of-an-element/index.tsx
- client/posts/drag-to-scroll/index.tsx
- client/posts/position-an-element-absolutely-to-another-element/index.tsx
- demo/create-a-custom-scrollbar/index.html
https://htmldom.dev/create-a-custom-scrollbar
> feat(post): Create a custom scrollbar

- client/posts/attach-or-detach-an-event-handler/index.tsx
> Minor typo fix

- README.md
> fixed typo "mordern" > "modern"

- posts/detect-the-dark-mode.md
If merged, this PR fixes a typo in the text.
> Fixes typo

- contents/add-a-special-message-when-users-copy-text.mdx
- contents/append-to-an-element.mdx
- contents/copy-highlighted-code-to-the-clipboard.mdx
- contents/copy-text-to-the-clipboard.mdx
- contents/paste-as-plain-text.mdx
https://phuoc.ng/collection/html-dom/add-a-special-message-when-users-copy-text/
> feat: Add a special message when users copy text

- contents/get-the-bounding-rectangle-of-a-text-node.mdx
https://phuoc.ng/collection/html-dom/get-the-bounding-rectangle-of-a-text-node/
> feat: Get the bounding rectangle of a text node

- contents/avoid-shifting-layout-when-opening-a-modal.mdx
- contents/calculate-the-size-of-scrollbar.mdx
- contents/check-if-an-element-is-a-descendant-of-another.mdx
- contents/detect-clicks-outside-of-an-element.mdx
https://phuoc.ng/collection/html-dom/avoid-shifting-layout-when-opening-a-modal/
> feat: Avoid shifting layout when opening a modal

- contents/make-a-text-area-auto-expand.mdx
https://phuoc.ng/collection/html-dom/make-a-text-area-auto-expand/
> feat: Make a textarea auto-expand

- contents/waiting-for-an-element-to-become-available.mdx
https://phuoc.ng/collection/html-dom/waiting-for-an-element-to-become-available/
> feat: Waiting for an element to become available

- contents/automatically-resize-an-iframe-when-its-content-height-changes.mdx
https://phuoc.ng/collection/html-dom/automatically-resize-an-iframe-when-its-content-height-changes/
> feat: Automatically resize an iframe when its content height changes

- contents/check-if-users-click-outside-of-selected-text.mdx
https://phuoc.ng/collection/html-dom/check-if-users-click-outside-of-selected-text/
> feat: Check if users click outside of selected text

- contents/display-a-confirm-modal-when-closing-the-browser.mdx
https://phuoc.ng/collection/html-dom/display-a-confirm-modal-when-closing-the-browser/
> feat: Display a confirm modal when closing the browser

- contents/display-a-modal-when-users-leave-website.mdx
https://phuoc.ng/collection/html-dom/display-a-modal-when-users-leave-website/
> feat: Display a modal when users leave website

- contents/show-an-addition-toolbar-after-users-select-text.mdx
https://phuoc.ng/collection/html-dom/show-an-addition-toolbar-after-users-select-text/
> feat: Show an addition toolbar after users selects text

- contents/count-how-many-lines-a-given-string-takes-up-in-a-text-area.mdx
- contents/measure-the-width-of-given-text-of-given-font.mdx
- contents/put-cursor-at-the-end-of-an-input.mdx
- contents/select-the-text-content-of-an-element.mdx
https://phuoc.ng/collection/html-dom/count-how-many-lines-a-given-string-takes-up-in-a-text-area/
> feat: Count how many lines a given string takes up in a text area

- contents/build-a-spin-input.mdx
https://phuoc.ng/collection/html-dom/build-a-spin-input/
> feat: Build a spin input

- contents/build-an-otp-input-field.mdx
https://phuoc.ng/collection/html-dom/build-an-otp-input-field/
> feat: Build an OTP input field

- contents/calculate-the-reading-time-of-a-webpage.mdx
https://phuoc.ng/collection/html-dom/calculate-the-reading-time-of-a-webpage/
> feat: Calculate the reading time of a webpage

- contents/create-a-custom-cursor.mdx
https://phuoc.ng/collection/html-dom/create-a-custom-cursor/
> feat: Create a custom cursor

- contents/dynamically-update-css-root-variables.mdx
https://phuoc.ng/collection/html-dom/dynamically-update-css-root-variables/
> feat: Dynamically update CSS root variables

- contents/sanitize-html-strings.mdx
https://phuoc.ng/collection/html-dom/sanitize-html-strings/
> feat: Sanitize HTML strings

- contents/detect-if-users-open-another-tab-of-the-current-page.mdx
https://phuoc.ng/collection/html-dom/detect-if-users-open-another-tab-of-the-current-page/
> feat: Detect if users open another tab of the current page

- contents/enter-full-screen-mode.mdx
https://phuoc.ng/collection/html-dom/enter-full-screen-mode/
> feat: Enter full-screen mode

- contents/get-or-set-the-cursor-position-in-a-content-editable-element.mdx
https://phuoc.ng/collection/html-dom/get-or-set-the-cursor-position-in-a-content-editable-element/
> feat: Get or set the cursor position in a contentEditable element

- contents/get-or-set-the-cursor-position-in-a-text-field.mdx
https://phuoc.ng/collection/html-dom/get-or-set-the-cursor-position-in-a-text-field/
> feat: Get or set the cursor position in a text field

- contents/indent-content-in-a-text-area-using-the-tab-key.mdx
https://phuoc.ng/collection/html-dom/indent-content-in-a-text-area-using-the-tab-key/
> feat: Indent content in a text area using the Tab key

- contents/insert-html-at-the-current-position-of-a-content-editable-element.mdx
https://phuoc.ng/collection/html-dom/insert-html-at-the-current-position-of-a-content-editable-element/
> feat: Insert HTML at the current position of a contentEditable element

- contents/insert-text-into-a-text-area-at-the-current-position.mdx
https://phuoc.ng/collection/html-dom/insert-text-into-a-text-area-at-the-current-position/
> feat: Insert text into a text area at the current position

- contents/move-the-cursor-to-the-end-of-a-content-editable-element.mdx
https://phuoc.ng/collection/html-dom/move-the-cursor-to-the-end-of-a-content-editable-element/
> feat: Move the cursor to the end of a contentEditable element

- contents/select-a-given-line-in-a-text-area.mdx
https://phuoc.ng/collection/html-dom/select-a-given-line-in-a-text-area/
> feat: Select a given line in a text area

- contents/jump-to-the-beginning-or-end-of-the-current-line-in-a-text-area.mdx
https://phuoc.ng/collection/html-dom/jump-to-the-beginning-or-end-of-the-current-line-in-a-text-area/
> feat: Jump to the beginning or end of the current line in a text area

- contents/add-a-special-message-when-users-copy-text.mdx
- contents/build-an-otp-input-field.mdx
- contents/change-the-favicon-dynamically-based-on-user-color-scheme-preference.mdx
- contents/display-a-modal-when-users-leave-website.mdx
- contents/insert-text-into-a-text-area-at-the-current-position.mdx
- contents/show-an-addition-toolbar-after-users-select-text.mdx
https://phuoc.ng/collection/html-dom/change-the-favicon-dynamically-based-on-user-color-scheme-preference/
> feat: Change the favicon dynamically
